apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: billing-application-set
  namespace: argocd
spec:
  generators:
    - clusters:
        selector:
          matchExpressions:
            - key: name
              operator: NotIn
              values: ["hub"]
  template:      
    metadata:
      name: 'test-billing-{{server}}'
    spec:
      # The project the application belongs to.
      project: default

      # Source of the application manifests
      source:
        repoURL: https://github.com/gyi-nbat2/gitops-cert-level-3-examples.git
        targetRevision: HEAD
        path: ./test-app/manifests
      
      # Destination cluster and namespace to deploy the application
      destination:
        server: '{{server}}'
        namespace: 'test'

      # Sync policy
      syncPolicy:
        syncOptions:
          - CreateNamespace=true  
        automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
          prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
          selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
      